export const tempData = {
  page: 1,
  results: [
    // {
    //   adult: false,
    //   backdrop_path: "/jnE1GA7cGEfv5DJBoU2t4bZHaP4.jpg",
    //   genre_ids: [28, 878],
    //   id: 1094844,
    //   original_language: "en",
    //   original_title: "Ape vs. Mecha Ape",
    //   overview:
    //     "Recognizing the destructive power of its captive giant Ape, the military makes its own battle-ready A.I., Mecha Ape. But its first practical test goes horribly wrong, leaving the military no choice but to release the imprisoned giant ape to stop the colossal robot before it destroys downtown Chicago.",
    //   popularity: 2106.85,
    //   poster_path: "/dJaIw8OgACelojyV6YuVsOhtTLO.jpg",
    //   release_date: "2023-03-24",
    //   title: "Ape vs. Mecha Ape",
    //   video: false,
    //   vote_average: 5.9,
    //   vote_count: 87,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg",
    //   genre_ids: [28, 878, 12],
    //   id: 823464,
    //   original_language: "en",
    //   original_title: "Godzilla x Kong: The New Empire",
    //   overview:
    //     "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
    //   popularity: 2229.531,
    //   poster_path: "/nVOZuxRiBygJ3VmXc9QcDGZfHzD.jpg",
    //   release_date: "2024-03-27",
    //   title: "Godzilla x Kong: The New Empire",
    //   video: false,
    //   vote_average: 6.51,
    //   vote_count: 931,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    //   genre_ids: [878, 12],
    //   id: 693134,
    //   original_language: "en",
    //   original_title: "Dune: Part Two",
    //   overview:
    //     "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    //   popularity: 1753.806,
    //   poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    //   release_date: "2024-02-27",
    //   title: "Dune: Part Two",
    //   video: false,
    //   vote_average: 8.236,
    //   vote_count: 3644,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/kYgQzzjNis5jJalYtIHgrom0gOx.jpg",
    //   genre_ids: [16, 28, 10751, 35, 14],
    //   id: 1011985,
    //   original_language: "en",
    //   original_title: "Kung Fu Panda 4",
    //   overview:
    //     "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    //   popularity: 1723.801,
    //   poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    //   release_date: "2024-03-02",
    //   title: "Kung Fu Panda 4",
    //   video: false,
    //   vote_average: 7.123,
    //   vote_count: 1503,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/4woSOUD0equAYzvwhWBHIJDCM88.jpg",
    //   genre_ids: [28, 27, 53],
    //   id: 1096197,
    //   original_language: "en",
    //   original_title: "No Way Up",
    //   overview:
    //     "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
    //   popularity: 1746.101,
    //   poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
    //   release_date: "2024-01-18",
    //   title: "No Way Up",
    //   video: false,
    //   vote_average: 6.382,
    //   vote_count: 584,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/tpiqEVTLRz2Mq7eLq5DT8jSrp71.jpg",
    //   genre_ids: [878, 28, 18],
    //   id: 934632,
    //   original_language: "en",
    //   original_title: "Rebel Moon - Part Two: The Scargiver",
    //   overview:
    //     "The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.",
    //   popularity: 1558.065,
    //   poster_path: "/cxevDYdeFkiixRShbObdwAHBZry.jpg",
    //   release_date: "2024-04-19",
    //   title: "Rebel Moon - Part Two: The Scargiver",
    //   video: false,
    //   vote_average: 6.11,
    //   vote_count: 658,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/5Eip60UDiPLASyKjmHPMruggTc4.jpg",
    //   genre_ids: [27, 9648, 53],
    //   id: 1041613,
    //   original_language: "en",
    //   original_title: "Immaculate",
    //   overview:
    //     "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
    //   popularity: 1300.38,
    //   poster_path: "/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg",
    //   release_date: "2024-03-20",
    //   title: "Immaculate",
    //   video: false,
    //   vote_average: 6.261,
    //   vote_count: 385,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg",
    //   genre_ids: [878, 27, 28],
    //   id: 940721,
    //   original_language: "ja",
    //   original_title: "ゴジラ-1.0",
    //   overview:
    //     "Postwar Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.",
    //   popularity: 1424.679,
    //   poster_path: "/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
    //   release_date: "2023-11-03",
    //   title: "Godzilla Minus One",
    //   video: false,
    //   vote_average: 7.871,
    //   vote_count: 710,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/v5XyXZe8FADw8iHupB4L7QOAwH9.jpg",
    //   genre_ids: [16, 35, 10751],
    //   id: 748783,
    //   original_language: "en",
    //   original_title: "The Garfield Movie",
    //   overview:
    //     "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
    //   popularity: 1091.629,
    //   poster_path: "/zK2sFxZcelHJRPVr242rxy5VK4T.jpg",
    //   release_date: "2024-04-30",
    //   title: "The Garfield Movie",
    //   video: false,
    //   vote_average: 6.4,
    //   vote_count: 31,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/ilK1JRbMjo4sMJtNKLOKnqRf1RH.jpg",
    //   genre_ids: [10752, 28, 36],
    //   id: 976906,
    //   original_language: "en",
    //   original_title: "Spitfire Over Berlin",
    //   overview:
    //     "August 1944. With the American Eighth Air Force poised to strike over Nazi Germany, British Intelligence learns that they could be flying into a deadly trap. With only hours to spare, Flight Lieutenant Edward Barnes must fly a life and death mission over Berlin in his unarmed Spitfire to obtain photographic evidence and save the lives of 1200 men.",
    //   popularity: 962.025,
    //   poster_path: "/xtPPOPTad1qopK6uDe3VlYUa22o.jpg",
    //   release_date: "2022-05-13",
    //   title: "Spitfire Over Berlin",
    //   video: false,
    //   vote_average: 3.8,
    //   vote_count: 18,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/6a3aiSYNqABoV1Fq8n10LMOBxhH.jpg",
    //   genre_ids: [28, 53],
    //   id: 821937,
    //   original_language: "vi",
    //   original_title: "578: Phát Đạn Của Kẻ Điên",
    //   overview:
    //     "A container truck driver, Hùng, lives an idyllic life with his little daughter, An. The father and daughter become the closest companions in every journey with their orange container truck. Life goes on like that until An has to leave her father to go to school. One day, Hùng is informed that An is suffering from severe depression. Relying on his old skills in the past and finding out the truth, Hùng becomes enraged and painful to know that his little girl was kidnapped by a male stranger. Starting his lone and intense journey looking for and chasing after the unknown abuser, Hùng realizes that to hunt down that psychopath he has to counter the massive underground forces behind him.",
    //   popularity: 1101.749,
    //   poster_path: "/8Nw5v7wPfa2FwbKyx61K2nIBcKa.jpg",
    //   release_date: "2022-05-20",
    //   title: "578: Magnum",
    //   video: false,
    //   vote_average: 5.16,
    //   vote_count: 25,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/qGJASuD3fs9ZBxuEZoxCLVidVq8.jpg",
    //   genre_ids: [12, 28, 18],
    //   id: 845111,
    //   original_language: "fr",
    //   original_title: "Les trois mousquetaires : Milady",
    //   overview:
    //     "D'Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.",
    //   popularity: 1093.541,
    //   poster_path: "/3biswIjw14uDVil12nMOxcTAfmH.jpg",
    //   release_date: "2023-12-13",
    //   title: "The Three Musketeers: Milady",
    //   video: false,
    //   vote_average: 6.496,
    //   vote_count: 377,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
    //   genre_ids: [878, 12, 28],
    //   id: 653346,
    //   original_language: "en",
    //   original_title: "Kingdom of the Planet of the Apes",
    //   overview:
    //     "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
    //   popularity: 990.656,
    //   poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    //   release_date: "2024-05-08",
    //   title: "Kingdom of the Planet of the Apes",
    //   video: false,
    //   vote_average: 6.767,
    //   vote_count: 15,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg",
    //   genre_ids: [16, 28, 12, 35, 10751],
    //   id: 940551,
    //   original_language: "en",
    //   original_title: "Migration",
    //   overview:
    //     "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    //   popularity: 882.885,
    //   poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    //   release_date: "2023-12-06",
    //   title: "Migration",
    //   video: false,
    //   vote_average: 7.481,
    //   vote_count: 1293,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg",
    //   genre_ids: [878, 28, 14, 12],
    //   id: 601796,
    //   original_language: "ko",
    //   original_title: "외계+인 1부",
    //   overview:
    //     "Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human's body. The two parties cross paths when a time-traveling portal opens up.",
    //   popularity: 909.24,
    //   poster_path: "/8QVDXDiOGHRcAD4oM6MXjE0osSj.jpg",
    //   release_date: "2022-07-20",
    //   title: "Alienoid",
    //   video: false,
    //   vote_average: 6.821,
    //   vote_count: 312,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg",
    //   genre_ids: [28, 14],
    //   id: 634492,
    //   original_language: "en",
    //   original_title: "Madame Web",
    //   overview:
    //     "Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.",
    //   popularity: 821.317,
    //   poster_path: "/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
    //   release_date: "2024-02-14",
    //   title: "Madame Web",
    //   video: false,
    //   vote_average: 5.613,
    //   vote_count: 1219,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/k0ucFBBgSDTXYU8fVHXJyjAuIIe.jpg",
    //   genre_ids: [27],
    //   id: 1063879,
    //   original_language: "fr",
    //   original_title: "Vermines",
    //   overview:
    //     "Residents of a rundown French apartment building battle against an army of deadly, rapidly reproducing spiders.",
    //   popularity: 837.471,
    //   poster_path: "/dY98PkUAbIGUUg0FhXEcOkbzHIZ.jpg",
    //   release_date: "2023-12-27",
    //   title: "Infested",
    //   video: false,
    //   vote_average: 7.027,
    //   vote_count: 164,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg",
    //   genre_ids: [18, 12],
    //   id: 618588,
    //   original_language: "en",
    //   original_title: "Arthur the King",
    //   overview:
    //     "Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.",
    //   popularity: 808.939,
    //   poster_path: "/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg",
    //   release_date: "2024-03-15",
    //   title: "Arthur the King",
    //   video: false,
    //   vote_average: 6.828,
    //   vote_count: 102,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/keVfqCMKmJ55nHzmqR2Q5K7LwJt.jpg",
    //   genre_ids: [28, 53, 10752],
    //   id: 784651,
    //   original_language: "hi",
    //   original_title: "फाइटर",
    //   overview:
    //     "Top IAF aviators come together in the face of imminent danger, to form Air Dragons. Fighter unfolds their camaraderie, brotherhood and battles, internal and external.",
    //   popularity: 884.768,
    //   poster_path: "/zDZowwb9GZGEctAu2PCpjiPQAMM.jpg",
    //   release_date: "2024-01-24",
    //   title: "Fighter",
    //   video: false,
    //   vote_average: 5.341,
    //   vote_count: 66,
    // },
    // {
    //   adult: false,
    //   backdrop_path: "/oe7mWkvYhK4PLRNAVSvonzyUXNy.jpg",
    //   genre_ids: [28, 53],
    //   id: 359410,
    //   original_language: "en",
    //   original_title: "Road House",
    //   overview:
    //     "Ex-UFC fighter Dalton takes a job as a bouncer at a Florida Keys roadhouse, only to discover that this paradise is not all it seems.",
    //   popularity: 804.24,
    //   poster_path: "/bXi6IQiQDHD00JFio5ZSZOeRSBh.jpg",
    //   release_date: "2024-03-08",
    //   title: "Road House",
    //   video: false,
    //   vote_average: 7.012,
    //   vote_count: 1671,
    // },
  ],
  total_pages: 43994,
  total_results: 879861,
};

export const temp = {
  adult: false,
  backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
  belongs_to_collection: {
    id: 726871,
    name: "Dune Collection",
    poster_path: "/wcVafar6Efk3YgFvh8oZQ4yHL6H.jpg",
    backdrop_path: "/ygVSGv86R0BTOKJIb8RQ1sFxs4q.jpg",
  },
  budget: 190000000,
  genres: [
    {
      id: 878,
      name: "Science Fiction",
    },
    {
      id: 12,
      name: "Adventure",
    },
  ],
  homepage: "https://www.dunemovie.com",
  id: 693134,
  imdb_id: "tt15239678",
  origin_country: ["US"],
  original_language: "en",
  original_title: "Dune: Part Two",
  overview:
    "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
  popularity: 1753.806,
  poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
  production_companies: [
    {
      id: 923,
      logo_path: "/8M99Dkt23MjQMTTWukq4m5XsEuo.png",
      name: "Legendary Pictures",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2024-02-27",
  revenue: 704300257,
  runtime: 167,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline: "Long live the fighters.",
  title: "Dune: Part Two",
  video: false,
  vote_average: 8.219,
  vote_count: 3671,
  videos: {
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Filmbooks: Water",
        key: "29zQBzteAh0",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-04-26T14:00:02.000Z",
        id: "662c1b6e91f0ea011fbd05c0",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Filmbooks: The Reverend Mother",
        key: "Faioi9RAoFE",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-04-19T14:00:19.000Z",
        id: "66229814e4b5760164bc8977",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "10 Minute Preview",
        key: "rJxVPQRrRxc",
        site: "YouTube",
        size: 1080,
        type: "Clip",
        official: true,
        published_at: "2024-04-15T12:07:27.000Z",
        id: "661d42e6e4886001853b88bd",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Filmbooks: House Corrino",
        key: "J-GWW9LIOb0",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-04-09T14:00:19.000Z",
        id: "661b1e3c15c636017e44b7a3",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "'Dune: Part Two' with Denis Villeneuve & more filmmakers | Academy Conversations",
        key: "6czYOLR3tBg",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-03-29T16:00:07.000Z",
        id: "660d79430b5fd6017c397208",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "This or That",
        key: "Xq6OPXGEzBo",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-03-08T07:57:42.000Z",
        id: "65ebc0ca28723c01643e7dd4",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Greig Fraser and the Cinematography of Dune: Part Two | The #DolbyInstitute Podcast",
        key: "39p8wPkhmtM",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: false,
        published_at: "2024-03-05T19:01:18.000Z",
        id: "65e798aeea4263014820ffec",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: '"#1 Movie in the World" - Now Playing',
        key: "tQucjg4-Q6M",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2024-03-05T17:52:20.000Z",
        id: "65e788c1e3294301869bce57",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Denis Villeneuve on Dune: Part Two",
        key: "N4StKUrf2ig",
        site: "YouTube",
        size: 2160,
        type: "Featurette",
        official: true,
        published_at: "2024-03-05T15:31:45.000Z",
        id: "65e74923ef8b320185d84a4f",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Director Denis Villenueve talks Dune Part Two",
        key: "asTOTXj5AtI",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: false,
        published_at: "2024-03-01T21:16:46.000Z",
        id: "65e2562141a5610148829da2",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: '"A Remarkable Achievement" - Now Playing',
        key: "vVPUM0QNK4M",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2024-03-01T18:07:22.000Z",
        id: "65e788caa6c1040187e81b9d",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Behind-the-Scenes Featurette",
        key: "un3uQ22WOCk",
        site: "YouTube",
        size: 1080,
        type: "Behind the Scenes",
        official: true,
        published_at: "2024-02-29T17:06:10.000Z",
        id: "65e1b026a806730184ab2718",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Love Dune More at Dolby Cinema",
        key: "xvKsRp_tkQs",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: false,
        published_at: "2024-02-28T14:38:16.000Z",
        id: "65e2570bdd25890186f22555",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: '"The Best Cast Assembled" - Tickets on Sale Now',
        key: "xwYNVhFJyYk",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2024-02-22T22:10:29.000Z",
        id: "65d7c7035f6c490185c6ac0f",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Destiny Featurette",
        key: "B3nTuXYxUto",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-02-19T16:40:56.000Z",
        id: "65d38d178de0ae0163d89e4b",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "IMAX Behind the Frame Clip [ENG SUB]",
        key: "gCqJEd6CftI",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-02-18T04:00:17.000Z",
        id: "65db8b8305b549017b18040b",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "World Premiere",
        key: "fT4O8mbD7g0",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-02-16T17:29:09.000Z",
        id: "65d0b9a4e62719014870c119",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "In Conversation With Nolan & Villeneuve | IMAX® Behind the Frame",
        key: "2-5KCpEhHho",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-02-09T20:00:08.000Z",
        id: "65dcb2db03bf840184b008df",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Extended Sneak Preview",
        key: "VC7-OcFvVEw",
        site: "YouTube",
        size: 1080,
        type: "Clip",
        official: true,
        published_at: "2024-02-08T22:27:54.000Z",
        id: "65cd63c0efcea9017ca9c1e9",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Austin Butler is Feyd-Rautha",
        key: "FfN_duZkntw",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-02-01T02:31:32.000Z",
        id: "65bb71877646fd0184bdf6c6",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Florence Pugh is Princess Irulan",
        key: "EfLtStz19r0",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2024-01-30T18:08:49.000Z",
        id: "65b9427d2f266b017de1d2f4",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Rise",
        key: "VHa103ITb68",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2024-01-29T00:00:12.000Z",
        id: "65b72ea51089ba017df7a26b",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Heart",
        key: "0QPxaoGh19I",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2024-01-28T20:49:35.000Z",
        id: "65b700030cd32a0163e60710",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Tickets on Sale Now",
        key: "136rl6tckGg",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2024-01-26T17:16:35.000Z",
        id: "65b432719ba86a00e42fe4f4",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer 3",
        key: "U2Qp5pL3ovA",
        site: "YouTube",
        size: 2160,
        type: "Trailer",
        official: true,
        published_at: "2023-12-12T17:00:20.000Z",
        id: "6578d2b3f04d0100c691f500",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer 2",
        key: "_YUzQa_1RCE",
        site: "YouTube",
        size: 2160,
        type: "Trailer",
        official: true,
        published_at: "2023-06-29T16:00:24.000Z",
        id: "649db24d5aba320139942fc7",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer",
        key: "Way9Dexny3w",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2023-05-02T15:06:46.000Z",
        id: "645141d9e942ee0e3a06c077",
      },
    ],
  },
};
